const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict');
const {ready,seek,read}=require('../a02/capture.cjs');
const out=path.resolve('docs/validation/a03-poster-remaster-2026-10-04'),baseline='8686c4d51d0414c80db5ae0377495fab2ec00005';
const files=['module-a/visual-director/fonts/narrative-serif.woff2','module-a/visual-director/fonts/narrative-sans.woff2','module-a/a01/app.mjs','module-a/a02/spatial.mjs','module-a/a03/composition.mjs','module-a/a03/lighting.mjs','module-a/a03/styles.css','module-a/a03/view.mjs','module-a/a03/progress.mjs','shuilong-temple/director-light.mjs','shuilong-temple/narrative-markers.mjs','shuilong-temple/水龙祠-交互预览.html'];
const bodies=new Map(files.map(f=>[f,execFileSync('git',['show',`${baseline}:${f}`],{maxBuffer:30*1024*1024})]));
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),report={baseline,rows:[],limitations:'同机 headless Chrome；帧间隔含浏览器调度，不等于GPU耗时或跨设备帧率。'};try{
for(const [width,height]of [[1920,1080],[1440,900]])for(const version of ['before','after']){const p=await b.newPage({viewport:{width,height}});if(version==='before')await p.route('**/*',r=>{const name=decodeURIComponent(new URL(r.request().url()).pathname).slice(1),body=bodies.get(name);return body?r.fulfill({status:200,body,contentType:name.endsWith('.woff2')?'font/woff2':name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'}):r.continue();});
const resources=[],pending=[];p.on('response',r=>{if(!/^https?:/.test(r.url()))return;pending.push((async()=>{try{const body=await r.body();resources.push({url:r.url(),bytes:body.length,status:r.status()});}catch{}})());});
const start=Date.now();await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);const readyMs=Date.now()-start;await seek(p,5.7);await Promise.allSettled(pending);const initialBytes=resources.reduce((a,r)=>a+r.bytes,0);await seek(p,9.65);await seek(p,11.7);const s=await read(p);await Promise.allSettled(pending);
const sample=await p.evaluate(async()=>{const intervals=[],scroll=[];for(const active of [false,true]){let previous=performance.now();for(let i=0;i<90;i++){if(active)scrollTo(0,(10.21+2.9*i/89)*innerHeight);await new Promise(requestAnimationFrame);const now=performance.now();(active?scroll:intervals).push(now-previous);previous=now;}}const stats=a=>({mean:a.reduce((x,y)=>x+y)/a.length,p95:a.toSorted((x,y)=>x-y)[Math.floor(a.length*.95)]});const c=document.querySelector('iframe').contentDocument.querySelector('canvas'),gl=c.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {idle:stats(intervals),scroll:stats(scroll),heap:performance.memory?.usedJSHeapSize??null,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable'};});
report.rows.push({width,height,version,readyMs,initialBytes,chapterBytes:resources.reduce((a,r)=>a+r.bytes,0),resourceCount:resources.length,stats:s.stats,canvases:s.canvas,sample,newAssets:resources.filter(r=>/a03\//.test(r.url))});await p.close();}
for(const width of [1920,1440]){const pair=report.rows.filter(r=>r.width===width);assert.equal(pair[0].stats.geometries,pair[1].stats.geometries);assert.equal(pair[0].stats.textures,pair[1].stats.textures);assert.equal(pair[1].canvases,1);assert.equal(pair[1].stats.post.enabled,false);}
fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(report,null,2));console.log('PASS: actual resource bytes, renderer counts, idle/scroll sampling; no added geometry, texture or canvas.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
