const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{PNG}=require('pngjs');
const out=path.resolve('docs/validation/a03-refinement-2026-10-04');
const baseline='c23615a99fb926a831fc7f811b4a00a168023112';
const sizes=[[1920,1080],[1440,900],[1366,768],[1024,768]];
const oldStates=[['01-a02-core',9.65],['02-transition-25',10.45],['03-transition-60',10.8],['04-poster-stable',11.7],['05-marker-stable',12.1],['06-handoff',12.92],['07-a04-entry',13.21]];
const ready=async p=>{await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.modelReady);await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getArchitectureState().every(m=>m.clonesLoaded));await p.evaluate(()=>Promise.all([document.fonts.ready,document.querySelector('iframe').contentDocument.fonts.ready,...[...document.images].filter(i=>i.src).map(i=>i.decode())]));};
const read=p=>p.evaluate(()=>{
 const f=document.querySelector('iframe'),r=f.getBoundingClientRect(),a=f.contentWindow.shuilongTemple,art=a.getA01ArtState();
 const box=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height};};
 const spans=[...document.querySelectorAll('.a03-title span')];
 return {screen:scrollY/innerHeight,phase:document.body.dataset.phase,frame:box(f),bounds:{left:r.x+art.bounds.left*r.width,right:r.x+art.bounds.right*r.width,top:r.y+art.bounds.top*r.height,bottom:r.y+art.bounds.bottom*r.height},env:a.getA01EnvironmentState(),stats:a.getA01RenderStats(),lighting:a.getDirectorState(),copy:box(document.querySelector('.a03-copy')),title:document.querySelector('.a03-title').getAttribute('aria-label'),hero:spans.map(e=>({text:e.textContent,opacity:Number(getComputedStyle(e).opacity),fontSize:parseFloat(getComputedStyle(e).fontSize),rect:box(e)})),text:[...document.querySelectorAll('.a03-copy p')].map(e=>({text:e.textContent,opacity:Number(getComputedStyle(e).opacity),rect:box(e),fits:e.scrollWidth<=e.clientWidth+1})),field:document.querySelector('.a02-field').style.opacity,fieldHidden:document.querySelector('.a02-field').hidden,labels:[...f.contentDocument.querySelectorAll('.mural-label')].filter(e=>!e.hidden).map(e=>({id:e.dataset.muralId,opacity:Number(e.style.opacity),rect:{x:r.x+box(e).x,y:r.y+box(e).y,w:box(e).w,h:box(e).h}})),anchors:[...f.contentDocument.querySelectorAll('#mural-lines circle')].map(e=>({x:e.style.display==='none'?null:e.getAttribute('cx'),y:e.style.display==='none'?null:e.getAttribute('cy'),display:e.style.display})),overflow:document.documentElement.scrollWidth>innerWidth,canvases:f.contentDocument.querySelectorAll('canvas').length,posterZ:document.querySelector('.a03-poster')?getComputedStyle(document.querySelector('.a03-poster')).zIndex:'2',buildingZ:getComputedStyle(document.querySelector('.model-shell')).zIndex};
});
const seek=async(p,n)=>{await p.evaluate(n=>scrollTo(0,n*innerHeight),n);await p.waitForTimeout(500);await ready(p);return read(p);};
const equivalent=s=>{const {name,...state}=s;return {...state,stats:undefined,lighting:undefined};};
function delta(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let changed=0,max=0;for(let i=0;i<a.data.length;i+=4){const d=Math.max(...[0,1,2].map(c=>Math.abs(a.data[i+c]-b.data[i+c])));if(d>4)changed++;max=Math.max(max,d);}return{changed:changed/(a.width*a.height),max};}

const states=[['01-entry',10.25],['02-poster',10.8],['03-roof-transition',11.4],['04-cutaway-stable',11.95],['05-markers',12.15],['06-fifth-focus',12.7],['07-handoff',13.195],['08-a04-entry',13.21],['09-a04-route-start',13.65]];
const files=['module-a/a01/app.mjs','module-a/a03/progress.mjs','module-a/a03/composition.mjs','module-a/a03/lighting.mjs','module-a/a03/view.mjs','module-a/a03/styles.css','shuilong-temple/a02-light.mjs','shuilong-temple/director-light.mjs','shuilong-temple/a01-environment.mjs','shuilong-temple/narrative-markers.mjs','shuilong-temple/水龙祠-交互预览.html'];
const bodies=new Map(files.map(f=>[f,execFileSync('git',['show',baseline+':'+f],{maxBuffer:30*1024*1024})]));
const extended=async p=>({...await read(p),roofs:await p.evaluate(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getRoofState()),handoff:await p.locator('.a03-handoff').evaluate(e=>({text:e.textContent,opacity:Number(getComputedStyle(e).opacity),rect:JSON.parse(JSON.stringify(e.getBoundingClientRect()))}))});
const stop=async(p,n)=>{await seek(p,n);return extended(p)};
const overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const serial=s=>JSON.stringify({...s,name:undefined,stats:undefined,lighting:undefined});
(async()=>{fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true}),report={baseline,sizes:[],errors:[],protection:[]};try{
for(const[width,height]of (process.argv.includes('protection-only')?[]:sizes)){const p=await b.newPage({viewport:{width,height}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.location().url))report.errors.push(m.text())});p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))report.errors.push(r.status()+' '+r.url())});await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);const rows=[];
for(const[name,n]of states){const s=await stop(p,n);assert.equal(s.overflow,false);assert.equal(s.canvases,1);assert.ok(s.roofs.every(r=>r.visible));if(n>=10.8&&n<13.2){assert.deepEqual(s.labels.map(l=>l.id),['mural-01','mural-02','mural-05']);for(const l of s.labels){assert.ok(l.rect.x>=0&&l.rect.y>=0&&l.rect.x+l.rect.w<=width&&l.rect.y+l.rect.h<=height,'label out of viewport');assert.ok(!overlaps(l.rect,s.copy),'label overlaps copy');}for(let i=0;i<s.labels.length;i++)for(let j=i+1;j<s.labels.length;j++)assert.ok(!overlaps(s.labels[i].rect,s.labels[j].rect),'label collision');}
if(n<10.85)assert.ok(s.roofs.every(r=>r.opacity===1));if(n===11.4)assert.ok(s.roofs.every(r=>Math.abs(r.opacity-.66)<.003));if(n>11.85&&n<12.85)assert.ok(s.roofs.every(r=>Math.abs(r.opacity-.15)<.0001));if(n>12.65&&n<13.2)assert.ok(s.labels.find(l=>l.id==='mural-05').opacity>s.labels.find(l=>l.id==='mural-01').opacity*2);
if(n===12.15){assert.ok(s.hero.every(t=>t.opacity===1));assert.ok(s.hero[1].rect.x<s.hero[0].rect.x,'swap lost');assert.equal(s.env.visible,true);assert.ok(s.env.visibility>.3);const text=await p.evaluate(()=>[...document.querySelector('iframe').contentDocument.querySelectorAll('.mural-label')].filter(e=>!e.hidden).map(e=>e.textContent));assert.deepEqual(text,['①第一铺','②第二铺','⑤第五铺']);}
await p.screenshot({path:path.join(out,'screenshots',width+'-'+name+'.png')});rows.push({name,...s});}
await stop(p,12.15);const held=serial(await extended(p));await p.waitForTimeout(600);assert.equal(serial(await extended(p)),held,'pause drift');for(const n of [11.95,12.05,12.15]){const s=await stop(p,n);s.screen=JSON.parse(held).screen;assert.equal(serial(s),held,'stable frame drifts');}
for(const row of rows.slice(0,7).toReversed())assert.equal(serial(await stop(p,row.screen)),serial(row),'reverse differs');
await stop(p,12.15);await p.reload();await ready(p);assert.equal(serial(await extended(p)),serial(rows.find(r=>r.name==='05-markers')),'refresh differs');await p.emulateMedia({reducedMotion:'reduce'});await stop(p,12.15);assert.ok((await extended(p)).roofs.every(r=>Math.abs(r.opacity-.15)<1e-6));await p.screenshot({path:path.join(out,'screenshots',width+'-reduced.png')});await p.emulateMedia({reducedMotion:'no-preference'});
await stop(p,12.15);await p.setViewportSize({width:1024,height:768});await p.waitForTimeout(500);assert.equal((await extended(p)).overflow,false);await p.setViewportSize({width,height});await p.waitForTimeout(500);
await stop(p,10.25);await p.mouse.wheel(0,height*1.9);await p.waitForTimeout(650);assert.equal((await extended(p)).phase,'a03-reading');for(let i=0;i<6;i++){await p.mouse.wheel(0,12);await p.waitForTimeout(50)}assert.equal((await extended(p)).phase,'a03-reading');
const boundary=[];for(const n of [13.195,13.199,13.2,13.201,13.205,13.21,13.25,13.4,13.55])boundary.push(await stop(p,n));for(let i=1;i<5;i++){assert.ok(Math.abs(boundary[i].bounds.left-boundary[i-1].bounds.left)<4,'camera jump');assert.ok(Math.abs(boundary[i].frame.w-boundary[i-1].frame.w)<4);assert.ok(Math.abs(boundary[i].roofs[0].opacity-boundary[i-1].roofs[0].opacity)<.002,'roof flash');const a=boundary[i-1].anchors[4],c=boundary[i].anchors[4];assert.ok(Math.hypot(Number(a.x)-Number(c.x),Number(a.y)-Number(c.y))<4,'fifth anchor jump');}
report.sizes.push({width,height,rows,boundary,pause:true,stable:true,reverse:true,refresh:true,resize:true,reduced:true,wheel:true});await p.close();console.log('PASS refinement '+width+'x'+height);
}
for(const[width,height]of sizes){const before=new Map(),anchors=new Map();for(const version of ['before','after']){const p=await b.newPage({viewport:{width,height}});if(version==='before')await p.route('**/*',r=>{const name=decodeURIComponent(new URL(r.request().url()).pathname).slice(1),body=bodies.get(name);return body?r.fulfill({status:200,body,contentType:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css':'text/javascript'}):r.continue()});await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);
for(const n of [.6,2.5,4,5.7,6.7,7.55,8.7,9.65,10.2,13.56]){await seek(p,n);if(n>13.2)await p.locator('.a03').evaluate(e=>e.style.opacity='0');const bytes=await p.screenshot();if(version==='before')before.set(n,bytes);else{const d=delta(before.get(n),bytes);if(!((d.max<=16&&d.changed<.005)||(d.max<=32&&d.changed<.0005))){fs.writeFileSync(path.join(out,'protected-before.png'),before.get(n));fs.writeFileSync(path.join(out,'protected-after.png'),bytes)}assert.ok((d.max<=16&&d.changed<.005)||(d.max<=32&&d.changed<.0005),'protected '+n+' '+JSON.stringify(d));report.protection.push({width,height,screen:n,...d});}}
await seek(p,12.15);const s=await read(p);if(version==='before'){anchors.set(width,s.anchors);if(width===1920)await p.screenshot({path:path.join(out,'before-1920.png')})}else assert.deepEqual(s.anchors,anchors.get(width),'real projections moved');await p.close();}console.log('PASS protected '+width+'x'+height)}
assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,process.argv.includes('protection-only')?'protection-results.json':'results.json'),JSON.stringify(report,null,2));console.log('PASS all refinement checks');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
