const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{PNG}=require('pngjs');
const out=path.resolve('docs/validation/a03-poster-remaster-2026-10-04');
const baseline='8686c4d51d0414c80db5ae0377495fab2ec00005';
const sizes=[[1920,1080],[1440,900],[1366,768],[1024,768]];
const states=[['01-a02-core',9.65],['02-transition-25',10.45],['03-transition-60',10.8],['04-poster-stable',11.7],['05-marker-stable',12.1],['06-handoff',12.92],['07-a04-entry',13.21]];
const ready=async p=>{await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.modelReady);await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getArchitectureState().every(m=>m.clonesLoaded));await p.evaluate(()=>Promise.all([document.fonts.ready,document.querySelector('iframe').contentDocument.fonts.ready,...[...document.images].filter(i=>i.src).map(i=>i.decode())]));};
const read=p=>p.evaluate(()=>{
 const f=document.querySelector('iframe'),r=f.getBoundingClientRect(),a=f.contentWindow.shuilongTemple,art=a.getA01ArtState();
 const box=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height};};
 const spans=[...document.querySelectorAll('.a03-title span')];
 return {screen:scrollY/innerHeight,phase:document.body.dataset.phase,frame:box(f),bounds:{left:r.x+art.bounds.left*r.width,right:r.x+art.bounds.right*r.width,top:r.y+art.bounds.top*r.height,bottom:r.y+art.bounds.bottom*r.height},env:a.getA01EnvironmentState(),stats:a.getA01RenderStats(),lighting:a.getDirectorState(),copy:box(document.querySelector('.a03-copy')),title:document.querySelector('.a03-title').getAttribute('aria-label'),hero:spans.map(e=>({text:e.textContent,opacity:Number(getComputedStyle(e).opacity),fontSize:parseFloat(getComputedStyle(e).fontSize),rect:box(e)})),text:[...document.querySelectorAll('.a03-copy p')].map(e=>({text:e.textContent,opacity:Number(getComputedStyle(e).opacity),rect:box(e),fits:e.scrollWidth<=e.clientWidth+1})),field:document.querySelector('.a02-field').style.opacity,fieldHidden:document.querySelector('.a02-field').hidden,labels:[...f.contentDocument.querySelectorAll('.mural-label')].filter(e=>!e.hidden).map(e=>({id:e.dataset.muralId,opacity:Number(e.style.opacity),rect:{x:r.x+box(e).x,y:r.y+box(e).y,w:box(e).w,h:box(e).h}})),anchors:[...f.contentDocument.querySelectorAll('#mural-lines circle')].map(e=>({x:e.style.display==='none'?null:e.getAttribute('cx'),y:e.style.display==='none'?null:e.getAttribute('cy'),display:e.style.display})),overflow:document.documentElement.scrollWidth>innerWidth,canvases:f.contentDocument.querySelectorAll('canvas').length,posterZ:document.querySelector('.a03-poster')?getComputedStyle(document.querySelector('.a03-poster')).zIndex:'2',buildingZ:getComputedStyle(document.querySelector('.model-shell')).zIndex};
});
const seek=async(p,n)=>{await p.evaluate(n=>scrollTo(0,n*innerHeight),n);await p.waitForTimeout(500);await ready(p);return read(p);};
const equivalent=s=>{const {name,...state}=s;return {...state,stats:undefined,lighting:undefined};};
function delta(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let changed=0,max=0;for(let i=0;i<a.data.length;i+=4){const d=Math.max(...[0,1,2].map(c=>Math.abs(a.data[i+c]-b.data[i+c])));if(d>4)changed++;max=Math.max(max,d);}return{changed:changed/(a.width*a.height),max};}
const files=['module-a/a01/app.mjs','module-a/a02/spatial.mjs','module-a/a03/styles.css','module-a/a03/progress.mjs','module-a/a03/view.mjs','module-a/a03/composition.mjs','module-a/a03/lighting.mjs','shuilong-temple/director-light.mjs','shuilong-temple/a02-light.mjs','shuilong-temple/a01-environment.mjs','shuilong-temple/narrative-markers.mjs','shuilong-temple/水龙祠-交互预览.html'];
const bodies=new Map(files.map(f=>[f,execFileSync('git',['show',`${baseline}:${f}`],{maxBuffer:30*1024*1024})]));
(async()=>{
 fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const report={baseline,browser:browser.version(),sizes:[],errors:[],networkFailures:[],optionalFailures:[],regression:[]};
 try{
 for(const[width,height]of (process.argv.includes('regression-only')?[]:sizes)){const p=await browser.newPage({viewport:{width,height}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.location().url||''))report.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)(r.url().endsWith('/favicon.ico')?report.optionalFailures:report.networkFailures).push({url:r.url(),status:r.status()});});p.on('requestfailed',r=>report.networkFailures.push({url:r.url(),error:r.failure()}));
 await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);const rows=[];
 for(const[name,n]of states){const s=await seek(p,n);assert.equal(s.overflow,false);assert.equal(s.canvases,1);if(n>10.75&&n<13.2)assert.deepEqual(s.labels.map(l=>l.id),['mural-01','mural-02','mural-05']);await p.screenshot({path:path.join(out,'screenshots',`${width}-${name}.png`)});rows.push({name,...s});}
 const stable=rows.find(r=>r.name==='04-poster-stable'),occupancy=(stable.bounds.right-stable.bounds.left)/width;
 assert.ok(occupancy>=.60&&occupancy<=.76,`building occupancy ${occupancy}`);assert.equal(stable.title,'出庙 · 入庙');assert.ok(stable.hero.every(t=>t.opacity===1&&t.fontSize>=150));assert.ok(stable.text.every(t=>t.fits&&t.opacity===1));assert.ok(stable.copy.y>=0&&stable.copy.y+stable.copy.h<height-28);assert.equal(stable.env.visible,true);assert.equal(stable.env.visibility,.38);assert.equal(stable.env.posterWeight,1);assert.equal(stable.field,'1');assert.ok(Number(stable.posterZ)<Number(stable.buildingZ));assert.equal(stable.lighting.exposure,1.10);assert.equal(stable.lighting.lights,4);
 for(const label of stable.labels){const a=label.rect,c=stable.copy;assert.ok(a.x>=c.x+c.w||a.y+a.h<=c.y||a.y>=c.y+c.h,'label overlaps copy');}
 assert.ok(stable.text[0].text.includes('三铺壁画分列两侧'));assert.ok(stable.text[1].text.includes('队伍从庙中出发，又重新归来'));
 assert.equal(await p.locator('.a03').evaluate(e=>/研究视角|李济民|第122页|从出行与归来/.test(e.textContent)),false);
 const handoff=rows.find(r=>r.name==='06-handoff');assert.ok(handoff.hero.every(h=>h.opacity===0));assert.ok(handoff.env.visibility<.05);assert.ok(handoff.labels.find(l=>l.id==='mural-05').opacity>handoff.labels.find(l=>l.id==='mural-01').opacity);
 await seek(p,11.7);const paused=equivalent(await read(p));await p.waitForTimeout(600);assert.deepEqual(equivalent(await read(p)),paused,'pause drifts');for(const n of [11.3,11.7,12.1]){const s=equivalent(await seek(p,n));s.screen=paused.screen;assert.deepEqual(s,paused,'stable interval moves');}
 for(const row of rows.toReversed())assert.deepEqual(equivalent(await seek(p,row.screen)),equivalent(row),'reverse differs');
 const reloads=[];for(const n of [11.7,12.92]){const original=equivalent(await seek(p,n));await p.reload();await ready(p);await p.waitForTimeout(600);assert.deepEqual(equivalent(await read(p)),original,'refresh differs');reloads.push(n);}
 for(const n of [9.65,13.21,11.7,10.2])await seek(p,n);
 await seek(p,10.2);await p.mouse.wheel(0,height*1.5);await p.waitForTimeout(650);assert.equal((await read(p)).phase,'a03-reading');for(let i=0;i<6;i++){await p.mouse.wheel(0,20);await p.waitForTimeout(40);}assert.equal((await read(p)).phase,'a03-reading');
 await seek(p,11.7);const resize=[];for(const[w,h]of [[1440,900],[1024,768],[1366,900],[width,height]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(650);const s=await read(p);assert.equal(s.phase,'a03-reading');assert.equal(s.overflow,false);assert.ok(s.hero.every(t=>t.opacity===1));resize.push({width:w,height:h,frame:s.frame});}
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(500);const reduced=await read(p);assert.ok(reduced.text.every(t=>t.opacity===1));assert.ok(reduced.hero.every(t=>t.opacity===1));assert.equal(reduced.env.visible,true);assert.deepEqual(reduced.labels.map(l=>l.id),['mural-01','mural-02','mural-05']);await p.screenshot({path:path.join(out,'screenshots',`${width}-reduced.png`)});await seek(p,13.21);assert.equal((await read(p)).env.visible,false);await p.emulateMedia({reducedMotion:'no-preference'});
 const boundary=[];for(const n of [13.195,13.199,13.2,13.201,13.205])boundary.push(await seek(p,n));for(let i=1;i<boundary.length;i++){assert.ok(Math.abs(boundary[i].frame.w-boundary[i-1].frame.w)<4);assert.ok(Math.abs(boundary[i].bounds.left-boundary[i-1].bounds.left)<4,'A04 camera jumps');}
 await seek(p,11.7);
 const complete=PNG.sync.read(await p.screenshot());
 await p.locator('.a03-poster').evaluate(e=>e.style.opacity='0');const withoutTitle=PNG.sync.read(await p.screenshot());
 await p.locator('.model-shell').evaluate(e=>e.style.visibility='hidden');await p.locator('.a03-poster').evaluate(e=>e.style.opacity='1');const titleOnly=PNG.sync.read(await p.screenshot());
 await p.locator('.a03-poster').evaluate(e=>e.style.opacity='0');const empty=PNG.sync.read(await p.screenshot());
 let glyphPixels=0,occludedPixels=0;for(let i=0;i<empty.data.length;i+=4){const d=Math.max(...[0,1,2].map(c=>Math.abs(titleOnly.data[i+c]-empty.data[i+c])));if(d>32){glyphPixels++;const visible=Math.max(...[0,1,2].map(c=>Math.abs(complete.data[i+c]-withoutTitle.data[i+c])));if(visible<4)occludedPixels++;}}
 const occlusion={glyphPixels,occludedPixels,fraction:occludedPixels/glyphPixels};assert.ok(occludedPixels>1000&&occlusion.fraction>.04&&occlusion.fraction<.55,'no real scene occlusion or excessive masking');
 report.sizes.push({width,height,occupancy,rows,occlusion,reverse:true,pause:true,stable:true,wheel:true,slowWheel:true,reloads,resize,reduced:true,boundary});await p.close();console.log(`PASS poster ${width}x${height}`);
 }
 // Pixel regression against the exact start-of-task sources; only A03/transition frames may change.
 for(const[width,height]of sizes){const before=new Map();for(const version of ['before','after']){const p=await browser.newPage({viewport:{width,height}});if(version==='before')await p.route('**/*',r=>{const name=decodeURIComponent(new URL(r.request().url()).pathname).slice(1),body=bodies.get(name);return body?r.fulfill({status:200,body,contentType:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'}):r.continue();});await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);
 for(const n of [.6,2.5,4,5.7,6.7,7.55,8.7,9.65,10.2,13.21]){await seek(p,n);if(n===13.21)await p.locator('.a03').evaluate(e=>e.style.opacity='0');const bytes=await p.screenshot();if(version==='before')before.set(n,bytes);else{const d=delta(before.get(n),bytes);if(!(((d.max<=16&&d.changed<.005)||(d.max<=32&&d.changed<.0005)))){fs.writeFileSync(path.join(out,'regression-before.png'),before.get(n));fs.writeFileSync(path.join(out,'regression-after.png'),bytes);fs.writeFileSync(path.join(out,'regression-failure.json'),JSON.stringify({width,height,screen:n,state:await read(p)}));}assert.ok(((d.max<=16&&d.changed<.005)||(d.max<=32&&d.changed<.0005)),`protected ${n} changed ${JSON.stringify(d)}`);report.regression.push({width,height,screen:n,excludeA03HandoffCopy:n===13.21,...d});}}
 if(version==='before'&&width===1920){await seek(p,11.7);await p.screenshot({path:path.join(out,'screenshots','before-1920.png')});}await p.close();}console.log(`PASS protected ${width}x${height}`);}
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.networkFailures,[]);fs.writeFileSync(path.join(out,process.argv.includes('regression-only')?'protection-results.json':'results.json'),JSON.stringify(report,null,2));console.log('PASS all poster/reverse/refresh/resize/reduced/continuous-boundary/regression checks');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
