const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{PNG}=require('pngjs');
const out=path.resolve('docs/validation/a03-high-fidelity-2026-10-04');
const baseline='b6ce49f90383534bb85c30d1251d8d2dab6cec7f';
const states=[['01-a02-stable',9.65],['02-a02-a03-transition',10.4],['03-a03-enter',10.85],['04-a03-reading',11.7],['05-a03-handoff',12.92],['06-a04-entry',13.21]];
const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};
const ready=async p=>{await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.modelReady);await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getArchitectureState().every(m=>m.clonesLoaded));await p.evaluate(()=>Promise.all([document.fonts.ready,document.querySelector('iframe').contentDocument.fonts.ready]));};
const read=p=>p.evaluate(()=>{const f=document.querySelector('iframe'),r=f.getBoundingClientRect(),api=f.contentWindow.shuilongTemple,a=api.getA01ArtState(),bounds=a.bounds;
  const box=e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};};
  return {screen:scrollY/innerHeight,phase:document.body.dataset.phase,frame:box(f),bounds:{left:r.x+bounds.left*r.width,right:r.x+bounds.right*r.width,top:r.y+bounds.top*r.height,bottom:r.y+bounds.bottom*r.height},env:api.getA01EnvironmentState(),art:a,stats:api.getA01RenderStats(),copy:box(document.querySelector('.a03-copy')),text:[...document.querySelectorAll('.a03-copy > *')].map(e=>({text:e.textContent,opacity:getComputedStyle(e).opacity,rect:box(e),fits:e.scrollWidth<=e.clientWidth+1})),labels:[...f.contentDocument.querySelectorAll('.mural-label')].filter(e=>!e.hidden).map(e=>({id:e.dataset.muralId,opacity:e.style.opacity,rect:{x:r.x+box(e).x,y:r.y+box(e).y,w:box(e).w,h:box(e).h}})),murals:api.getMurals(),overflow:document.documentElement.scrollWidth>innerWidth,canvases:f.contentDocument.querySelectorAll('canvas').length};});
const seek=async(p,n)=>{await p.evaluate(n=>scrollTo(0,n*innerHeight),n);await p.waitForTimeout(450);await ready(p);return read(p);};
function diff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let changed=0,max=0;for(let i=0;i<a.data.length;i+=4){const d=Math.max(...[0,1,2].map(c=>Math.abs(a.data[i+c]-b.data[i+c])));if(d)changed++;max=Math.max(max,d);}return {changed:changed/(a.width*a.height),max};}
const equivalent=s=>{const {name,...state}=s;return {...state,stats:undefined,art:{...s.art,lighting:undefined}};};
(async()=>{fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const report={baseline,browser:browser.version(),sizes:[],errors:[],networkFailures:[],optionalFailures:[],regression:[]};try{
for(const [width,height]of [[1920,1080],[1440,900]]){const p=await browser.newPage({viewport:{width,height}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.location().url||''))report.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)(r.url().endsWith('/favicon.ico')?report.optionalFailures:report.networkFailures).push({url:r.url(),status:r.status()});});p.on('requestfailed',r=>report.networkFailures.push({url:r.url(),error:r.failure()}));await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);
 const rows=[];for(const[name,n]of states){const s=await seek(p,n);assert.equal(s.overflow,false);assert.equal(s.canvases,1);if(n>10.75&&n<13.2)assert.deepEqual(s.labels.map(l=>l.id),['mural-01','mural-02','mural-05']);await p.screenshot({path:path.join(out,'screenshots',`${width}-${name}.png`)});if(name==='04-a03-reading')await p.screenshot({path:path.join(out,'screenshots',`${width}-reading-detail.png`),clip:{x:width*.05,y:height*.18,width:width*.54,height:height*.60}});rows.push({name,...s});}
 const reading=rows.find(r=>r.name==='04-a03-reading');const occupancy=(reading.bounds.right-reading.bounds.left)/width;assert.ok(occupancy>=.45&&occupancy<=.70,`building occupancy ${occupancy}`);assert.ok(reading.bounds.left<reading.copy.x+reading.copy.w+width*.06,'building remains isolated');assert.ok(reading.bounds.right>width*.80);assert.ok(reading.text.every(t=>t.fits&&Number(t.opacity)===1));assert.ok(reading.copy.y>=0&&reading.copy.y+reading.copy.h<height-65);assert.equal(reading.env.visible,false);for(const l of reading.labels){assert.ok(l.rect.x>=reading.copy.x+reading.copy.w||l.rect.y>=reading.copy.y+reading.copy.h||l.rect.y+l.rect.h<=reading.copy.y,'label overlaps copy');assert.ok(l.rect.x>=0&&l.rect.x+l.rect.w<=width);}
 await seek(p,11.7);const pause=equivalent(await read(p));await p.waitForTimeout(500);assert.deepEqual(equivalent(await read(p)),pause,'pause changes reading');for(const n of [11.3,11.7,12.1]){await seek(p,n);const state=equivalent(await read(p));state.screen=pause.screen;assert.deepEqual(state,pause,'reading interval moves');}
 for(const row of rows.toReversed()){assert.deepEqual(equivalent(await seek(p,row.screen)),equivalent(row),'reverse differs');}for(const n of [10.25,10.65,11,11.7,12.5,13.1,13.21,12.92,11.7,10.4,9.65])await seek(p,n);
 // Real wheel, slow steps, jump scroll and refresh derive the same reading state.
 await seek(p,10.2);await p.mouse.wheel(0,height*1.5);await p.waitForTimeout(600);assert.equal((await read(p)).phase,'a03-reading');for(let i=0;i<6;i++){await p.mouse.wheel(0,20);await p.waitForTimeout(40);}assert.equal((await read(p)).phase,'a03-reading');await seek(p,11.7);await p.reload();await ready(p);assert.equal((await read(p)).phase,'a03-reading');await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(400);const reduced=await read(p);assert.ok(reduced.text.every(t=>Number(t.opacity)===1));assert.deepEqual(reduced.bounds,reading.bounds);await p.screenshot({path:path.join(out,'screenshots',`${width}-reduced.png`)});
 // Sample both sides of the A04 boundary; small steps may not create a size jump.
 await p.emulateMedia({reducedMotion:'no-preference'});const boundary=[];for(const n of [13.195,13.199,13.2,13.201,13.205])boundary.push(await seek(p,n));for(let i=1;i<boundary.length;i++){assert.ok(Math.abs(boundary[i].frame.w-boundary[i-1].frame.w)<4,'A04 canvas jump');assert.ok(Math.abs(boundary[i].bounds.left-boundary[i-1].bounds.left)<4,'A04 camera jump');}
 report.sizes.push({width,height,occupancy,rows,reverse:true,pause:true,stable:true,wheel:true,slowWheel:true,jumps:true,reload:true,reduced:true,boundary});await p.close();
}
// Intercept actual modified sources with Git baseline, then compare protected scenes.
const files=['module-a/a01/app.mjs','module-a/a03/styles.css','module-a/a03/progress.mjs','module-a/a03/view.mjs','shuilong-temple/director-light.mjs','shuilong-temple/narrative-markers.mjs','shuilong-temple/水龙祠-交互预览.html'];const bodies=new Map(files.map(f=>[f,execFileSync('git',['show',`${baseline}:${f}`],{maxBuffer:30*1024*1024})]));
for(const[width,height]of [[1920,1080],[1440,900]]){const before=new Map();for(const version of ['before','after']){const p=await browser.newPage({viewport:{width,height}});if(version==='before')await p.route('**/*',r=>{const name=decodeURIComponent(new URL(r.request().url()).pathname).slice(1),body=bodies.get(name);return body?r.fulfill({status:200,body,contentType:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'}):r.continue();});await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);for(const n of [.6,2.5,4,5.7,6.7,7.55,8.7,9.65,10.2,13.21]){await seek(p,n);const bytes=await p.screenshot();if(version==='before')before.set(n,bytes);else{const delta=diff(before.get(n),bytes);assert.ok(delta.max<=4||delta.changed<.0005,`protected scene ${n} changed ${JSON.stringify(delta)}`);report.regression.push({width,height,screen:n,...delta});}}await p.close();}}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.networkFailures,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log('PASS: A03 composition, protected baseline scenes, continuous A04 boundary, two sizes, wheel, slow scroll, reverse, refresh, reduced motion, console and network.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
