const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{createHash}=require('node:crypto');
const baseline='8d6517f5cb2303c3c875202fb13c45d91c4f6e63',out=path.resolve('docs/validation/a05-a08-high-fidelity-2026-10-05');
const files=['module-a/guide','module-a/a05','module-a/a06','module-a/a07','module-a/a08'].flatMap(dir=>fs.readdirSync(dir).filter(f=>/\.(mjs|cjs)$/.test(f)).map(f=>dir+'/'+f));
for(const file of files)execFileSync(process.execPath,['--check',file]);
const protectedPaths=['module-a/a01','module-a/a02','module-a/a03','module-a/a04','Mural-Exhibition','shuilong-temple','水龙祠壁画素材'];
assert.equal(execFileSync('git',['diff',baseline,'--',...protectedPaths],{maxBuffer:40*1024*1024}).toString(),'');
const hash=buffer=>createHash('sha256').update(buffer).digest('hex');
const resources=['01','02','05'].map(id=>{const file=`水龙祠壁画素材/网页展示图/mural-${id}-display.webp`,current=fs.readFileSync(file),original=execFileSync('git',['show',`${baseline}:${file}`],{maxBuffer:40*1024*1024});assert.equal(hash(current),hash(original));return{file,bytes:current.length,sha256:hash(current),unchanged:true};});
const archiveRefs=execFileSync('git',['rev-parse','module-a-lofi-final-v1.0^{}','archive/module-a-lofi']).toString().trim().split(/\r?\n/);assert.ok(archiveRefs.every(ref=>ref==='48f272497e86e4549c5bcd0dee275ff347171a3f'));
const html=fs.readFileSync('shuilong-temple/水龙祠-交互预览.html','utf8');execFileSync(process.execPath,['--input-type=module','--check'],{input:html.match(/<script type="module">([\s\S]*?)<\/script>/)[1],maxBuffer:30*1024*1024});
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'build-results.json'),JSON.stringify({baseline,syntaxFiles:files,protectedPaths,protectedDiffEmpty:true,resources,archiveRefs,noBundler:true,modelRebuilt:false},null,2));console.log('PASS: native build/syntax, A01–A04/B/model protection, exact original display hashes and fixed archive refs');
