const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const base=path.resolve('docs/validation/a05-a08-high-fidelity-2026-10-05');
const report=JSON.parse(fs.readFileSync(path.join(base,'gallery-results.json')));
assert.deepEqual(report.sizes.map(r=>r.tag),['1920x1080','1440x900','1366x768','1024x768']);assert.deepEqual(report.errors,[]);assert.equal(report.refresh.length,6);assert.equal(report.resize.length,10);assert.ok(report.reduced.length>15&&report.fontFallback.length>15);
for(const size of report.sizes){assert.equal(size.rows.length,26);assert.ok(size.reverse&&size.stopStable);assert.ok(size.textContrast.body>=4.5&&size.textContrast.cta>=4.5);for(const row of size.rows){assert.ok(fs.existsSync(path.join(base,'after',`${row.name}-${size.tag}.webp`)));if(row.state.readingContrast)assert.ok(row.state.readingContrast>=4.5);}}
const docs=['docs/A05_PROTOTYPE.md','docs/A06_PROTOTYPE.md','docs/A07_PROTOTYPE.md','docs/A08_PROTOTYPE.md','docs/HIFI_VISUAL_SPEC.md','docs/DESIGN_SPEC.md',path.join(base,'README.md')];let links=0;
for(const file of docs){const text=fs.readFileSync(file,'utf8');assert.ok(text.includes('尚未视觉冻结'));assert.equal((text.match(/^```/gm)||[]).length%2,0);assert.ok(!/^(<<<<<<<|=======|>>>>>>>)/m.test(text));for(const match of text.matchAll(/\]\(([^)]+)\)/g)){const target=match[1];if(/^(https?:|#)/.test(target))continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),target.split('#')[0])),file+' -> '+target);links++;}}
for(const file of ['01-current-before.webp','09-a05-a08-contact-sheet.webp','10-responsive.webp','11-reading-and-scan.webp','12-entry-and-focus.webp'])assert.ok(fs.existsSync(path.join(base,file)));
execFileSync('git',['diff','--check','--','module-a',...docs],{stdio:'pipe'});
fs.writeFileSync(path.join(base,'delivery-results.json'),JSON.stringify({fourSizes:true,chapterSamples:104,defaultHoverFocus:true,refresh:report.refresh,resize:report.resize,reducedMotion:true,fontFallback:true,errors:[],documents:docs,links,whiteSpace:true,reviewQuestions:15},null,2));console.log('PASS: complete evidence, local doc links, candidate status and whitespace');
