const {chromium}=require('playwright'),sharp=require('sharp'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=path.resolve('docs/validation/a05-a08-high-fidelity-2026-10-05'),url='http://127.0.0.1:4175/module-a/a01/';
const sizes=process.env.GALLERY_VIEWPORTS?JSON.parse(process.env.GALLERY_VIEWPORTS):[[1920,1080],[1440,900],[1366,768],[1024,768]];
const scenes=[['a04-wall',17.6],['a05-transfer',17.8],['a05-intro',18.95],['a05-reading-1',19.75],['a05-reading-2',20.55],['a05-right',21.2],['a05-center',22.8],['a05-left',24.4],['a05-handoff',24.8],['a06-transfer',25.2],['a06-intro',25.95],['a06-reading-1',26.75],['a06-reading-2',27.55],['a06-right',28.2],['a06-center',29.8],['a06-left',31.4],['a07-transfer',32.2],['a07-intro',32.85],['a07-reading-1',33.45],['a07-reading-2',34.05],['a07-reading-3',34.65],['a07-right',35.2],['a07-center',37.3],['a07-left',39.5],['a08-half',40.5],['a08',42]];
const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};
async function read(page){return page.evaluate(()=>{
 const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};
 const guide=[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).map(g=>({chapter:g.dataset.chapter,opacity:+getComputedStyle(g).opacity,phase:g.dataset.phase,scan:+g.dataset.scanProgress,stage:+g.dataset.introStage,image:rect(g.querySelector('img')),src:g.querySelector('img').currentSrc,transform:g.querySelector('img').style.transform,shadow:getComputedStyle(g.querySelector('img')).boxShadow,intro:+getComputedStyle(g.querySelector('.mural-guide__intro')).opacity,veil:+getComputedStyle(g.querySelector('.mural-guide__veil')).opacity,marker:{text:g.querySelector('.mural-guide__marker').textContent,size:parseFloat(getComputedStyle(g.querySelector('.mural-guide__marker')).fontSize),background:getComputedStyle(g.querySelector('.mural-guide__marker')).backgroundColor},axis:rect(g.querySelector('.mural-guide__axis')),rail:rect(g.querySelector('.mural-guide__rail')),point:rect(g.querySelector('.mural-guide__rail b')),layers:[...g.querySelectorAll('.mural-guide__reading')].map(l=>({opacity:+getComputedStyle(l).opacity,rect:rect(l),text:l.textContent,scroll:getComputedStyle(l).overflowY}))}));
 const a08=document.querySelector('.a08'),api=document.querySelector('iframe').contentWindow.shuilongTemple;
 return{screen:scrollY/innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,guide,a08:{hidden:a08.hidden,opacity:+getComputedStyle(a08).opacity,inert:a08.inert,panel:rect(a08.querySelector('.a08__panel')),cta:rect(a08.querySelector('a')),href:a08.querySelector('a').href},stats:api.getA01RenderStats(),canvasCount:[...document.querySelectorAll('canvas'),...document.querySelector('iframe').contentDocument.querySelectorAll('canvas')].length};
 });}
async function seek(page,point){await page.evaluate(p=>scrollTo(0,p*innerHeight),point);await page.waitForTimeout(170);if(point>=17.4)await page.waitForFunction(()=>[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).every(g=>g.querySelector('img').naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function shot(page,name,tag){const file=path.join(out,'after',`${name}-${tag}.webp`);await sharp(await page.screenshot()).webp({quality:92}).toFile(file);}
async function contrast(page,selector){
 const el=page.locator(selector),data=await el.evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,color:getComputedStyle(e).color.match(/[\d.]+/g).slice(0,3).map(Number)}});
 await el.evaluate(e=>e.style.visibility='hidden');const {data:pixels,info}=await sharp(await page.screenshot()).removeAlpha().raw().toBuffer({resolveWithObject:true});await el.evaluate(e=>e.style.visibility='');
 const lum=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),a=lum(data.color);let minimum=100;
 for(let y=Math.ceil(data.y+4);y<data.y+data.h-4;y+=4)for(let x=Math.ceil(data.x+2);x<data.x+data.w-2;x+=4){const i=(y*info.width+x)*info.channels,b=lum([...pixels.subarray(i,i+3)]);minimum=Math.min(minimum,(Math.max(a,b)+.05)/(Math.min(a,b)+.05));}return minimum;
}
(async()=>{fs.mkdirSync(path.join(out,'after'),{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const report={sizes:[],resize:[],refresh:[],reduced:[],fontFallback:[],errors:[]};
 try{
  for(const [width,height]of sizes){const page=await browser.newPage({viewport:{width,height}}),tag=`${width}x${height}`;page.on('pageerror',e=>report.errors.push(e.message));const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(url);await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow?.modelReady);await seek(page,14.5);await page.locator('[data-skip]').click();const rows=[];
   for(const [name,point]of scenes){await seek(page,point);const state=await read(page);assert.equal(state.overflow,false,name);assert.equal(state.canvasCount,1);for(const g of state.guide){if(point>=18&&g.opacity>.99){assert.equal(g.shadow,'none');assert.ok(g.marker.size>=12&&g.marker.size<=14);assert.ok(g.marker.text.startsWith('A'));assert.equal(g.marker.background,'rgba(0, 0, 0, 0)');if(g.intro>.99)for(const l of g.layers.filter(l=>l.opacity>.99)){assert.ok(l.rect.x>=0&&l.rect.bottom<height*.9,`${name} text fits ${JSON.stringify(l.rect)}`);assert.notEqual(l.scroll,'auto');}if(g.phase==='scan'){assert.equal(g.intro,0);assert.equal(g.veil,0);assert.match(g.transform,/^translate3d\(/);assert.ok(Math.abs(g.image.height/height-.88)<.001||width<=1100&&Math.abs(g.image.height/height-.86)<.001);}}}
    if(name.endsWith('-right')){const g=state.guide.at(-1);assert.ok(Math.abs(g.image.right-width)<1);assert.equal(g.scan,0);assert.ok(Math.abs((g.point.x+2.5)-g.rail.right)<1);}
    if(name.endsWith('-left')){const g=state.guide.at(-1);assert.ok(Math.abs(g.image.x)<1);assert.equal(g.scan,1);assert.ok(Math.abs((g.point.x+2.5)-g.rail.x)<1);}
    if(name==='a08-half'||name==='a08')assert.deepEqual(state.guide[0].image,rows.find(r=>r.name==='a07-left').state.guide[0].image,'same image bounding box throughout A08');
    if(name==='a05-reading-2'||name==='a07-reading-3'){const chapter=name.startsWith('a05')?'05':'07',selector=`.mural-guide[data-chapter="${chapter}"] .mural-guide__description .mural-guide__reading:last-child`;const value=await contrast(page,selector);assert.ok(value>=4.5,name+' body contrast '+value);state.readingContrast=value;}
    await shot(page,name,tag);rows.push({name,state});
   }
   const textContrast={body:await contrast(page,'.a08__panel p:nth-of-type(2)'),cta:await contrast(page,'.a08 a')};assert.ok(textContrast.body>=4.5&&textContrast.cta>=4.5,JSON.stringify(textContrast));assert.ok((await read(page)).a08.cta.height>=44);
   await page.locator('.a08 a').hover();await page.waitForTimeout(270);await shot(page,'a08-hover',tag);await page.mouse.move(2,2);await page.keyboard.press('Tab');await page.locator('.a08 a').focus();assert.ok(await page.locator('.a08 a').evaluate(e=>e.matches(':focus-visible')));assert.equal(await page.locator('.a08 a').evaluate(e=>getComputedStyle(e).outlineWidth),'2px');await shot(page,'a08-focus',tag);
   for(const [name,point]of [...scenes].reverse()){await seek(page,point);const current=await read(page),previous=rows.find(r=>r.name===name).state;for(const g of current.guide){const old=previous.guide.find(o=>o.chapter===g.chapter);assert.equal(g.stage,old.stage);assert.ok(Math.abs(g.image.x-old.image.x)<1&&Math.abs(g.image.width-old.image.width)<1,name+' reverse '+JSON.stringify({before:old.image,after:g.image}));}if(point<40)assert.equal(current.a08.hidden,true);}
   for(const point of [22.8,29.8,37.3]){await seek(page,point);const before=await read(page);await page.waitForTimeout(300);assert.deepEqual((await read(page)).guide.map(g=>g.image),before.guide.map(g=>g.image),'stop scroll is stable');}
   if(width===1440){for(const point of [18.95,22.8,29.8,32.85,39.4,42]){await seek(page,point);const before=await read(page);await page.reload();await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow?.modelReady);await page.waitForFunction(()=>[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).every(g=>g.querySelector('img').naturalWidth>0));await page.waitForTimeout(170);const after=await read(page);assert.ok(Math.abs(after.screen-before.screen)<.002);assert.deepEqual(after.guide.map(g=>[g.stage,g.image]),before.guide.map(g=>[g.stage,g.image]));report.refresh.push(point);}
    for(const point of [17.6,18.95,20.55,22.8,24.8,25.2,34.65,37.3,40.5,42]){await seek(page,point);const before=await read(page);await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(250);const small=await read(page);assert.ok(Math.abs(small.screen-point)<.002);assert.deepEqual(small.guide.map(g=>[g.chapter,g.stage]),before.guide.map(g=>[g.chapter,g.stage]));for(let i=0;i<small.guide.length;i++)assert.ok(Math.abs(small.guide[i].scan-before.guide[i].scan)<.001,'integer scroll-pixel rounding');await page.setViewportSize({width,height});await page.waitForTimeout(250);const after=await read(page);assert.deepEqual(after.guide.map(g=>g.stage),before.guide.map(g=>g.stage));for(let i=0;i<after.guide.length;i++)assert.ok(Math.abs(after.guide[i].image.x-before.guide[i].image.x)<2&&Math.abs(after.guide[i].image.width-before.guide[i].image.width)<2);report.resize.push(point);}
    await seek(page,42);await page.locator('.a08 a').click();await page.waitForURL('http://localhost:3000/index.html');await page.waitForSelector('canvas',{state:'attached'});await page.goBack();await page.waitForFunction(()=>!document.querySelector('.a08').hidden&&document.querySelector('iframe')?.contentWindow?.modelReady);assert.ok(Math.abs((await read(page)).screen-42)<.02);
   }
   assert.equal(requests.filter(u=>/detail\.webp/.test(u)).length,0);report.sizes.push({tag,rows,textContrast,reverse:true,stopStable:true});await page.close();console.log('gallery '+tag+' PASS');
  }
  for(const reduced of [true,false]){const page=await browser.newPage({viewport:{width:1024,height:768},reducedMotion:reduced?'reduce':'no-preference'});if(!reduced)await page.route('**/*.woff2',r=>r.abort());await page.goto(url);await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow?.modelReady);
   for(const [name,point]of scenes.filter(([name])=>/intro|reading|right|left|^a08$/.test(name))){await seek(page,point);const state=await read(page);if(name.endsWith('-right'))assert.ok(Math.abs(state.guide.at(-1).image.right-1024)<1);if(name.endsWith('-left'))assert.ok(Math.abs(state.guide.at(-1).image.x)<1);for(const g of state.guide)if(g.intro>.99)for(const l of g.layers.filter(l=>l.opacity>.99))assert.ok(l.rect.bottom<720);if(name==='a08'){assert.ok(state.a08.cta.height>=44&&!state.a08.inert);await shot(page,reduced?'reduced':'font-fallback','1024x768');}report[reduced?'reduced':'fontFallback'].push(name);}
   await page.close();
  }
  assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,'gallery-results.json'),JSON.stringify(report,null,2));console.log('PASS: reading, direction, exact carry, reverse, resize, reload, focus, actual B return, fallback and reduced motion');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
