const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict');
const baseline='8d6517f5cb2303c3c875202fb13c45d91c4f6e63',out=path.resolve('docs/validation/a05-a08-high-fidelity-2026-10-05');
const overrides=['module-a/guide/controller.mjs','module-a/guide/progress.mjs','module-a/guide/styles.css','module-a/a05/content.mjs','module-a/a06/content.mjs','module-a/a07/content.mjs','module-a/a08/controller.mjs','module-a/a08/styles.css','module-a/visual-director/styles.css','module-a/visual-director/fonts/narrative-serif.woff2','module-a/visual-director/fonts/narrative-sans.woff2'];
async function sample(page,from,to){return page.evaluate(async({from,to})=>{const intervals=[];let last;for(let i=0;i<90;i++){await new Promise(resolve=>requestAnimationFrame(now=>{if(last)intervals.push(now-last);last=now;scrollTo(0,(from+(to-from)*i/89)*innerHeight);resolve()}));}intervals.sort((a,b)=>a-b);const api=document.querySelector('iframe').contentWindow.shuilongTemple;return{samples:intervals.length,median:intervals[Math.floor(intervals.length/2)],p95:intervals[Math.floor(intervals.length*.95)],stats:api.getA01RenderStats(),canvases:document.querySelector('iframe').contentDocument.querySelectorAll('canvas').length};},{from,to});}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),report={baseline,runs:[]};try{for(const mode of ['before','after']){const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();if(mode==='before')for(const file of overrides){const body=execFileSync('git',['show',`${baseline}:${file}`],{maxBuffer:20*1024*1024});await page.route('**/'+file,r=>r.fulfill({body,contentType:file.endsWith('.css')?'text/css':file.endsWith('.woff2')?'font/woff2':'text/javascript'}));}
 await page.goto('http://127.0.0.1:4175/module-a/a01/');await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow?.modelReady);const firstScreenFontBytes=await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.includes('narrative-')&&r.name.endsWith('.woff2')).reduce((s,r)=>s+r.transferSize,0));assert.equal(firstScreenFontBytes,0);
 for(const point of [14.5,18.95,25.95,32.85]){await page.evaluate(p=>scrollTo(0,p*innerHeight),point);await page.waitForTimeout(300);if(point===14.5)await page.locator('[data-skip]').click();if(point>=18)await page.waitForFunction(()=>[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).every(g=>g.querySelector('img').naturalWidth>0));}
 const timing=await sample(page,mode==='before'?34.2:35.2,39.4);await page.evaluate(()=>scrollTo(0,42*innerHeight));await page.waitForTimeout(250);
 const resources=await page.evaluate(()=>[window,document.querySelector('iframe').contentWindow].flatMap(w=>w.performance.getEntriesByType('resource').filter(r=>/mural-(01|02|05)-display\.webp|detail\.webp|woff2|glb/.test(r.name)).map(r=>({name:r.name,transferBytes:r.transferSize,encodedBytes:r.encodedBodySize,durationMs:r.duration}))));assert.equal(resources.filter(r=>r.name.includes('detail.webp')).length,0);assert.equal(timing.canvases,1);assert.equal(timing.stats.post.enabled,false);
 report.runs.push({mode,firstScreenFontBytes,timing,resources});await context.close();console.log('performance '+mode+' captured');}
 const [before,after]=report.runs;assert.equal(after.timing.stats.geometries,before.timing.stats.geometries);assert.equal(after.timing.stats.textures,before.timing.stats.textures);
 report.fontFiles=JSON.parse(fs.readFileSync('module-a/visual-director/fonts/manifest.json')).fonts.map(f=>({file:f.file,bytes:f.bytes}));report.limit='Single Chrome/headless host, 1440×900, two fresh contexts, 89 moving-frame intervals each. Does not measure GPU duration or establish cross-device performance.';
 fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(report,null,2));console.log('PASS: same renderer/canvas, geometry and GPU texture counts; no new mural or first-screen font requests');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
