const {chromium}=require('playwright'),{execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {seek,read,out}=require('./capture.cjs');
const baseline='65e76a187ebdb56a1b877fe9ddb61f2beefc9d08';
const files=execFileSync('git',['-c','core.quotepath=false','diff','--name-only',baseline],{encoding:'utf8'}).trim().split(/\r?\n/).filter(f=>/\.(mjs|css|html|woff2|json)$/.test(f));
const old=new Map(files.map(f=>[f,execFileSync('git',['show',baseline+':'+f],{maxBuffer:30*1024*1024})]));
async function frameTiming(p,moving=false){return p.evaluate(async moving=>{const f=document.querySelector('iframe'),api=f.contentWindow.shuilongTemple,values=[],mod=moving?await import('/module-a/a04/path.mjs'):null,base=api.getA04State();let last=performance.now();for(let i=0;i<130;i++){if(moving){const s=mod.sampleTour(8+10*i/129,base.overviewCamera);api.setA04({...base,...s,mode:'playing',routeComplete:false,elapsed:8+10*i/129,entryProgress:1,guideStartProgress:0,routeOpacity:1});}await new Promise(requestAnimationFrame);const now=performance.now();if(i>=10)values.push(now-last);last=now;}const gl=f.contentDocument.querySelector('canvas').getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {mean:values.reduce((a,b)=>a+b)/values.length,p95:values.toSorted((a,b)=>a-b)[Math.floor(values.length*.95)],samples:values.length,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null};},moving);}
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),rows=[];try{for(const[w,h]of [[1920,1080],[1440,900]])for(const version of ['before','after']){const p=await b.newPage({viewport:{width:w,height:h}});if(version==='before')await p.route('**/*',r=>{const file=decodeURIComponent(new URL(r.request().url()).pathname).slice(1),body=old.get(file);return body?r.fulfill({body,contentType:file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.woff2')?'font/woff2':'text/javascript; charset=utf-8'}):r.continue();});await p.goto('http://127.0.0.1:4175/module-a/a01/');await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.modelReady);await seek(p,14.5);await p.locator('[data-skip]').click();await p.waitForTimeout(300);
// Render the same complete A02 world in both versions before measuring. Three
// only counts GPU buffers after first use; a cold jump into roofless legacy A04
// otherwise omits roof/environment buffers and makes the memory comparison invalid.
await seek(p,8.8);await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getArchitectureState().every(m=>m.base&&m.roughness&&m.normal));await p.waitForTimeout(1500);await seek(p,12.15);await seek(p,14.5);await p.locator('[data-skip]').click();await p.waitForTimeout(500);
for(const[name,t]of version==='before'?[['fifth',9],['first',24],['second',37],['summary',58]]:[['fifth',6.5],['first',20],['second',34],['summary',45]]){await p.evaluate(async t=>{const api=document.querySelector('iframe').contentWindow.shuilongTemple,{sampleTour}=await import('/module-a/a04/path.mjs'),base=api.getA04State(),s=sampleTour(t,base.overviewCamera);window.perfTour={...base,...s,mode:'playing',elapsed:t,routeComplete:t>=45,entryProgress:1,guideStartProgress:0,routeOpacity:1};api.setA04(window.perfTour);},t);await p.waitForTimeout(500);await p.evaluate(()=>document.querySelector('iframe').contentWindow.shuilongTemple.setA04(window.perfTour));const timing=await frameTiming(p),state=await read(p);rows.push({w,h,version,name,timing,stats:state.stats});console.log(w,version,name,JSON.stringify(state.stats));}
rows.push({w,h,version,name:'moving-route',timing:await frameTiming(p,true),stats:(await read(p)).stats});await p.close();}
for(const[w]of [[1920],[1440]]){const a=rows.find(r=>r.w===w&&r.version==='before'&&r.name==='summary'),c=rows.find(r=>r.w===w&&r.version==='after'&&r.name==='summary');assert.ok(c.stats.geometries<a.stats.geometries);assert.ok(c.stats.textures<=a.stats.textures);}
fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify({baseline,worldPrewarm:'A02 8.8 screens with full roofs/environment, architectural maps ready, 1500 ms settle; A03 12.15 then A04.',rows,limits:'Same-machine headless Chrome. 120 frames after 10 warmup frames; frame intervals include scheduling, not GPU duration or cross-device guarantees. Local cutaway retains opaque roofs and submits their original triangles.'},null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
