const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {open,seek,read,out}=require('./capture.cjs');
const shot=async(p,dir,name)=>{fs.mkdirSync(dir,{recursive:true});await p.screenshot({path:path.join(dir,name+'.png')});};
async function sample(p,t){await p.evaluate(async t=>{const f=document.querySelector('iframe'),api=f.contentWindow.shuilongTemple,{sampleTour}=await import('/module-a/a04/path.mjs'),{caption}=await import('/module-a/a04/copy.mjs');const old=api.getA04State(),s=sampleTour(t,old.overviewCamera);const state={...old,...s,mode:'playing',elapsed:t,routeComplete:t===45,entryProgress:1,guideStartProgress:0,secondaryOpacity:1,routeOpacity:1};api.setA04(state);window.a04ReviewState=state;
const c=caption(s,t===45?'completed':'playing');document.querySelector('.a04 [data-title]').textContent=c.title;document.querySelector('.a04 [data-description]').textContent=c.description;document.querySelector('.a04 [data-number]').textContent=c.number;
},t);await p.waitForTimeout(500);await p.evaluate(()=>document.querySelector('iframe').contentWindow.shuilongTemple.setA04(window.a04ReviewState));await p.waitForTimeout(100);}
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),rows=[],errors=[];try{
for(const[w,h]of [[1920,1080],[1440,900],[1366,768],[1024,768]]){const p=await open(b,w,h);p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text());});const dir=path.join(out,'viewports',String(w));
await p.evaluate(()=>window.originalWorld=document.querySelector('iframe').contentWindow.shuilongTemple.getSharedWorldIdentity());
for(const[name,n]of [['a03-poster',12.15],['01-a03-end',13.2],['02-a04-entry',13.4]]){await seek(p,n);await shot(p,dir,name);}
const boundary=await p.evaluate(()=>{const el=document.querySelector('.a04-boundary'),box=el.getBoundingClientRect(),style=getComputedStyle(el);return {left:box.left,top:box.top,right:box.right,bottom:box.bottom,fontSize:style.fontSize,color:style.color};});
assert.ok(boundary.left>w*.5&&boundary.top>h*.75&&boundary.right<w&&boundary.bottom<h);assert.equal(boundary.fontSize,'13px');assert.equal(boundary.color,'rgb(181, 182, 173)');
await seek(p,14.5);await p.locator('[data-skip]').click();await p.waitForTimeout(200);
for(const[name,t]of [['04-a04-fifth',6.5],['05-a04-travel-first',13],['06-a04-first',20],['07-a04-return-second',27],['08-a04-second',34],['09-a04-withdraw',39],['10-a04-route-summary',45]]){await sample(p,t);const s=await read(p);assert.equal(s.canvas,1);assert.equal(s.world.environment,0);assert.equal(s.world.vegetation,0);assert.equal(s.world.mountains,0);assert.equal(s.cutaway.movie.active,true);
const protectedState=await p.evaluate(()=>{const a=document.querySelector('iframe').contentWindow.shuilongTemple;return {identity:a.getSharedWorldIdentity().root===window.originalWorld.root,roofs:a.getRoofState(),materials:['mural-05','mural-01','mural-02'].flatMap(id=>{const root=a.getSharedWorldIdentity().root,group=root.getObjectByName(id);return group.children.filter(m=>m.userData.role==='display').map(m=>({id,toneMapped:m.material.toneMapped,fog:m.material.fog}));}),nodes:[...document.querySelector('iframe').contentDocument.querySelectorAll('.a04-node')].filter(e=>getComputedStyle(e).display!=='none').map(e=>({text:e.textContent,current:e.dataset.current,opacity:e.style.opacity,left:e.getBoundingClientRect().left,top:e.getBoundingClientRect().top})),caption:document.querySelector('.a04-caption').getBoundingClientRect().toJSON()};});
assert.equal(protectedState.identity,true);assert.ok(protectedState.roofs.every(r=>r.visible&&r.opacity===1&&r.depthWrite));assert.ok(protectedState.materials.every(m=>!m.toneMapped&&!m.fog));assert.ok(protectedState.nodes.filter(n=>n.current==='true').length<=1);if(t===45){assert.equal(protectedState.nodes.length,3);assert.ok(s.state.bounds.left>0&&s.state.bounds.right<1&&s.state.bounds.top>.04&&s.state.bounds.bottom<.94);}
await shot(p,dir,name);rows.push({w,h,name,...s,...protectedState});}
for(const[name,n]of [['11-a04-fifth-handoff',17.6],['12-a05-entry',18.1]]){await seek(p,n);await shot(p,dir,name);}
// Fast forward/reverse clears every A04 object and restores the shared environment.
for(const n of [12.15,18.8,12.15,18.8,14.5,12.15])await seek(p,n);
const restored=await p.evaluate(()=>{const f=document.querySelector('iframe'),a=f.contentWindow.shuilongTemple;return {tour:a.getA04State(),world:a.getSharedWorldState(),nodes:[...f.contentDocument.querySelectorAll('.a04-node')].filter(e=>e.style.display!=='none').length,route:a.getSharedWorldIdentity().root.parent.getObjectByName('A04-route').visible,body:document.body.dataset.a04Mode,guide:document.querySelector('.mural-guide').hidden};});assert.equal(restored.tour,null);assert.equal(restored.nodes,0);assert.equal(restored.route,false);assert.equal(restored.world.chapter,'A03');assert.ok(restored.world.environment>0);assert.equal(restored.body,undefined);assert.equal(restored.guide,true);
await p.emulateMedia({reducedMotion:'reduce'});await seek(p,14.5);assert.equal((await read(p)).state.mode,'completed');assert.equal(await p.locator('[data-skip]:visible').count(),0);await shot(p,dir,'reduced-motion');await p.close();console.log(w,'review PASS');}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'review.json'),JSON.stringify({manualSeekUsesProductionPureState:true,realPlaybackEvidence:'after/states.json',rows,errors,quickCrossing:true,reducedMotion:true},null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
