const {chromium}=require('playwright'),{PNG}=require('pngjs'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('docs/validation/module-a-visual-director-v2/review');fs.mkdirSync(out,{recursive:true});
const manifest=JSON.parse(fs.readFileSync('module-a/visual-director/fonts/manifest.json','utf8'));
const seek=async(p,n)=>{await p.evaluate(n=>scrollTo(0,n*innerHeight),n);await p.waitForTimeout(350);await p.evaluate(()=>document.fonts.ready);};
const lum=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
async function textContrast(p,selector){const el=p.locator(selector),data=await el.evaluate(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e).color;return{rect:{x:r.x,y:r.y,w:r.width,h:r.height},color:c.match(/[\d.]+/g).slice(0,3).map(Number)};});await el.evaluate(e=>e.style.visibility='hidden');const png=PNG.sync.read(await p.screenshot());await el.evaluate(e=>e.style.visibility='');let minimum=100;const r=data.rect;for(let y=Math.ceil(r.y+6);y<r.y+r.h-6;y+=3)for(let x=Math.ceil(r.x+2);x<r.x+r.w-2;x+=3){const i=(y*png.width+x)*4;minimum=Math.min(minimum,contrast(data.color,[...png.data.subarray(i,i+3)]));}return minimum;}
(async()=>{const report={sizes:[],palettes:[],errors:[]};for(const [width,height]of [[1440,900],[1024,768],[1366,768],[1920,1080]]){const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width,height}});p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:4173/module-a/a01/');await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.modelReady);await p.waitForFunction(()=>document.querySelector('iframe').contentWindow.shuilongTemple.getArchitectureState().every(m=>m.clonesLoaded));await p.evaluate(()=>document.fonts.ready);
const firstFontBytes=await p.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.includes('narrative-')&&r.name.endsWith('woff2')).reduce((s,r)=>s+r.transferSize,0));assert.equal(firstFontBytes,0);
const layouts=[];for(const n of [7.4,8.03,8.20,8.38,8.6,9.7,11.7,15,17.4,17.6,17.8,18,19.3,22.3,29.5,37,42]){await seek(p,n);if(n===15&&await p.locator('[data-skip]').isVisible()){await p.locator('[data-skip]').click();await p.waitForTimeout(200);}if(n>=18)await p.waitForFunction(()=>[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).every(g=>g.querySelector('img').naturalWidth>0));const s=await p.evaluate(()=>{const f=document.querySelector('iframe'),a=f.contentWindow.shuilongTemple,r=f.getBoundingClientRect(),rect=e=>{const x=e.getBoundingClientRect();return{x:x.x,y:x.y,w:x.width,h:x.height};};return{screen:scrollY/innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,frame:rect(f),art:a.getA01ArtState(),stats:a.getA01RenderStats(),director:a.getDirectorState(),labels:[...f.contentDocument.querySelectorAll('.mural-label')].filter(e=>!e.hidden&&Number(e.style.opacity)>.01).map(e=>({id:e.dataset.muralId,opacity:Number(e.style.opacity),...rect(e)})),routes:[...f.contentDocument.querySelectorAll('.route-node-label')].filter(e=>getComputedStyle(e).display!=='none').map(rect),head:rect(document.querySelector('.a02 header')),foot:rect(document.querySelector('.a02 footer')),guide:[...document.querySelectorAll('.mural-guide')].filter(g=>!g.hidden).map(g=>({chapter:g.dataset.chapter,scan:Number(g.dataset.scanProgress),travel:Number(g.dataset.travelPx),veil:Number(getComputedStyle(g.querySelector('.mural-guide__veil')).opacity),intro:Number(getComputedStyle(g.querySelector('.mural-guide__intro')).opacity)})),env:a.getA01EnvironmentState().visible,oldEnv:a.getVisualState().visible};});assert.equal(s.overflow,false);assert.equal(s.env,false);assert.equal(s.oldEnv,false);assert.equal(s.stats.post.enabled,false);if(n>=20.3&&n<40)for(const g of s.guide){assert.equal(g.veil,0);assert.equal(g.intro,0);}if(n===11.7){const heading=await p.locator('.a03-title').evaluate(e=>e.textContent);assert.equal(heading,'从出行与归来，看壁画之间的联系');}
if(n===15){assert.equal(s.routes.length,3,'three overview nodes remain visible');for(const r of s.routes)assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=s.frame.w&&r.y+r.h<=s.frame.h);}
for(const e of s.labels)assert.ok(e.x>=0&&e.y>=0&&e.x+e.w<=s.frame.w+1&&e.y+e.h<=s.frame.h+1,'label leaves iframe');
if([7.4,8.6,9.7,11.7,15,42].includes(n))layouts.push(s);}
// Review all live heading text against the serif subset, including state titles reached in normal playback regressions.
const missing=await p.evaluate(text=>[...document.querySelectorAll('.a02 h2,.a03 h2,.a04 h2,.mural-guide h2,.a08 h2')].flatMap(e=>[...e.textContent].filter(c=>!c.trim()?false:!text.includes(c))),manifest.titleText);assert.deepEqual(missing,[]);
await seek(p,42);const cta=await textContrast(p,'.a08 a'),body=await textContrast(p,'.a08__panel p:nth-of-type(2)');assert.ok(cta>=4.5,`CTA contrast ${cta}`);assert.ok(body>=4.5,`A08 body contrast ${body}`);assert.ok(await p.locator('.a08 a').evaluate(e=>e.getBoundingClientRect().height>=44));
const beforeImage=await p.locator('.mural-guide[data-chapter="07"] img').boundingBox();await seek(p,39.5);const afterImage=await p.locator('.mural-guide[data-chapter="07"] img').boundingBox();assert.deepEqual(afterImage,beforeImage,'A08 inherits exact image placement');
const fontResources=await p.evaluate(()=>[window,document.querySelector('iframe').contentWindow].flatMap(w=>w.performance.getEntriesByType('resource').filter(r=>r.name.endsWith('.woff2')).map(r=>({name:r.name,bytes:r.transferSize,encoded:r.encodedBodySize}))));report.sizes.push({width,height,firstFontBytes,ctaContrast:cta,bodyContrast:body,fontResources,layouts});
if(width===1440||width===1024)for(const palette of ['warm','gray-green','gray-brown']){await p.evaluate(name=>{document.body.dataset.directorAccent=name;document.querySelector('iframe').contentDocument.body.dataset.directorAccent=name;},palette);for(const [scene,n]of [['markers',9.7],['route',15],['cta',42]]){await seek(p,n);if(n===15&&await p.locator('[data-skip]').isVisible())await p.locator('[data-skip]').click();await p.screenshot({path:path.join(out,`${palette}-${scene}-${width}x${height}.png`)});}report.palettes.push({width,height,palette,ctaContrast:await textContrast(p,'.a08 a')});}
}finally{await b.close();}console.log(`review: ${width}x${height}`);}assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log('PASS: visual layers, three nodes, local fonts, image continuity, contrast, palette comparisons');})().catch(e=>{console.error(e);process.exitCode=1;});
