const{chromium}=require('playwright'),{execFileSync}=require('node:child_process');const{out,seek,read,ready}=require('./capture.cjs');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const baseline='d8fe7edd7d995df0c5aef00de551b98761bcf413';
const replaced=['module-a/a01/app.mjs','module-a/a01/ink-scene.mjs','module-a/a01/cinematic-state.mjs','shuilong-temple/director-light.mjs','shuilong-temple/narrative-markers.mjs','shuilong-temple/水龙祠-交互预览.html'];
const bodies=new Map(replaced.map(p=>[p,execFileSync('git',['show',`${baseline}:${p}`],{maxBuffer:20*1024*1024})]));
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const report={baseline,browser:b.version(),rows:[],limitations:'Same machine, headless installed Chrome; frame intervals include browser scheduling. No GPU-time or cross-device claim.'};try{
for(const [width,height]of [[1440,900],[1024,768]])for(const version of ['before','after']){
 const context=await b.newContext({viewport:{width,height}}),p=await context.newPage();if(version==='before')await p.route('**/*',async route=>{const url=new URL(route.request().url()),relative=decodeURIComponent(url.pathname).slice(1),body=bodies.get(relative);if(body)await route.fulfill({status:200,body,contentType:relative.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8'});else await route.continue();});
 const resources=[],pending=[];p.on('response',response=>{if(!/^https?:/.test(response.url()))return;pending.push((async()=>{try{const body=await response.body();resources.push({url:response.url(),bytes:body.length,status:response.status()});}catch{}})());});
 const start=Date.now();await p.goto('http://127.0.0.1:4173/module-a/a01/');await ready(p);const modelReadyMs=Date.now()-start;await seek(p,5.7);await Promise.allSettled(pending);const firstLoadBytes=resources.reduce((n,r)=>n+r.bytes,0),firstRequests=resources.length;
 await seek(p,9.65);const scene=await read(p);await Promise.allSettled(pending);
 const timing=await p.evaluate(async()=>{const times=[];let previous=performance.now();for(let i=0;i<90;i++){await new Promise(requestAnimationFrame);const now=performance.now();times.push(now-previous);previous=now;}times.sort((a,b)=>a-b);const f=document.querySelector('iframe'),canvas=f.contentDocument.querySelector('canvas'),gl=canvas.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {frameMeanMs:times.reduce((a,b)=>a+b,0)/times.length,frameP95Ms:times[Math.floor(times.length*.95)],heapBytes:performance.memory?.usedJSHeapSize??null,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable',devicePixelRatio};});
 const scrollTiming=await p.evaluate(async()=>{const times=[];let previous=performance.now();for(let i=0;i<90;i++){scrollTo(0,(7.4+2.3*i/89)*innerHeight);await new Promise(requestAnimationFrame);const now=performance.now();times.push(now-previous);previous=now;}times.sort((a,b)=>a-b);return {meanMs:times.reduce((a,b)=>a+b,0)/times.length,p95Ms:times[Math.floor(times.length*.95)]};});
 assert.equal(scene.canvas,1);assert.equal(scene.post.enabled,false);assert.equal(scene.post.error,null);
 report.rows.push({size:[width,height],version,modelReadyMs,firstLoadBytes,firstRequests,chapterBytes:resources.reduce((n,r)=>n+r.bytes,0),scene:{stats:scene.stats,post:scene.post,director:scene.director,geometryCount:scene.stats.geometries,textureCount:scene.stats.textures},timing,scrollTiming,resources});await context.close();
}
 for(const size of [[1440,900],[1024,768]]){const pair=report.rows.filter(r=>String(r.size)===String(size));assert.equal(pair[0].scene.geometryCount,pair[1].scene.geometryCount);assert.equal(pair[0].scene.textureCount,pair[1].scene.textureCount);assert.equal(pair[1].scene.director.newPostTargets,0);}
 fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(report,null,2));console.log('PASS: measured cold bytes, resource counts, renderer stats, existing target storage, idle and scrolling frame intervals.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
